---
title: Atividade - Introdução à Máxima Parcimônia

date: "last-modified"
date-format: "long"

license: "CC BY-SA 4.0"

author:
  - name: Gabriel Rodrigues
    degrees:
      - MSc
    id: gr
    orcid: 0009-0005-2294-2845
    email: gvpina.rodrigues@gmail.com
    affiliation:
      - name: Universidade Estadual de Santa Cruz
        city: Ilhéus
        state: Bahia
        url: www.uesc.br

format:
  pdf:
    pdf-engine: xelatex
    sansfont: "LibreCaslonText"
    sansfontoptions:
      - Path = ./LibreCaslonText/
      - Extension = .ttf
      - UprightFont = *-Regular
      - BoldFont = *-Bold
      - ItalicFont = *-Italic
---

# Perguntas

## Questão 01) O que representam as politomias na topologia de uma árvore filogenética?

Uma politomia representa uma região de uma árvore filogenética onde a relação dos grupos não pôde ser resolvida em uma *dicotomia*. Em termos práticos, é um nó que diverge em 3 ou mais ramos em uma árvore filogenética.

A interpretação de uma politomia envolve a revisão dos dados inseridos na árvore, pois esse tipo de conformação pode representar a falta de informação suficiente para determinar a ordem de ramificação.

## Questão 02) Por quê o número de árvores enraizadas dicotômicas é tão maior que o de árvores não-enraizadas possíveis?

Geralmente é devido à baixa complexidade das árvores não-enraizadas quando comparadas às enraizadas.

Uma árvore dicotômica adiciona camadas de complexidado ao conferir a dimensão de tempo e sentido entre os nós da árvore, de forma que os elementos se configurem em forma ordinal (em uma ordem sequencial). Quando o nó *A* é ligado ao *B* e ao *C*, sendo assim por diante até o *F*, temos o total de **6 nós** que poderiam trocar de posição em uma árvore de forma ordinal.

Em uma árvore não-enraizada, por exemplo, o nó *C* poderia derivar os 3 nós restantes (D, E e F). Diminuindo o fator ordinal dos objetos da árvore, e consequentemente diminuindo as possibilidades de diferentes configurações de árovores filogenéticas.

## Questão 03) Diferenciar grupos *monofiléticos*, *parafiléticos* e *polifiléticos*.

Grupos monofiléticos, como o próprio nome sugere, possuem o mesmo ancestral comum em uma árvore filogenética. São os agrupamentos de OTUs que possuem um ancestral comum exclusivo juntamente com todos os seus descendentes.

Parafilia é o fenômeno onde grupos com a mesma origem ancestral são excluídos da árvore por terem um conjunto de descendentes distinto.

Grupos polifiléticos compartilham dois ou mais grupos monofiléticos em sua constituição. 

## Questão 04) Qual a relação conceitual entre *Grupo Externo*, *Plesiomorfias* e *Apomorfias*?

Um grupo externo é um conjunto de OTUs que pode ser utilizado como referência para enraizar uma árvore filogenética. 

Plesiomorfias e Apomorfias só podem ser analisadas de forma correta com o uso do adequado de grupos externos, permitindo o correto contraste entre as OTUs analisadas, permitindo a melhor análise entre Plesiomorfias e Apomorfias. Caso um grupo externo seja muito próximo dos objetos em análise, ele pode ser lido como uma plesiomorfia juntamente com o grupo ancestral.

A comparação com o grupo externo que dá sentido de tempo na análise de um grupo.

## Questão 05) Por quê Grupos Externos não podem ser testados como tal na mesma análise filogenética?

A escolha de um grupo externo deve ser feita a partir de testes anteriores, para garantir que indiquem que são OTUs próximas, mas que divergiram necessariamente antes do processo de diferenciação das OTUs do próprio grupo interno.

## Questão 06) Qual o critério para selecionar uma árvore de máxima parcimônia?

São necessários sítios informativos entre as amostras. Ou seja, é possível dividir as amostras em pelo menos dois grupos a partir das informações dos sítios informativos.

## Questão 07) Qual a regra básica para que um sitio com variação seja informativo para máxima Parcimônia.

É necessário que o sítio de variação divida as amostras em pelo menos dois grupos, com no mínimo dois representantes para cada grupo.

## Questão 08) Por quê foi chamada atenção que a árvore mais curta não é uma proibição à natureza?

Não necessariamente o processo evolutivo vai convergir sempre para a seleção de mudanças mais curtas ou de menos complexidade. A escolha de seleção do algoritimo não reflete processos biológicos reais, que por seleção, podem ocorrer de forma imprevisível e aleatória.

## Questão 09) O que está por trás do princípio que transições são mais frequentes que transversões? E por que alguns autores sugerem dar peso zero as transições?

Mutações 

## Questão 10) Por que em sequências codificadoras de proteínas a terceira base dos códons apresenta menores restrições evolutivas?